services:
  db:
    image: postgres:16
    container_name: mymaru
    environment:
      POSTGRES_DB: mymaruDB
      POSTGRES_USER: maru
      POSTGRES_PASSWORD: 5656
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: